In [48]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [49]:
x.dtype

dtype('int64')

In [50]:
x.shape

(5,)

In [51]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [52]:
Y.shape

(4, 3)

In [53]:
Y.size

12

In [54]:
x = np.array(['hello', 'world'])
print(x)

['hello' 'world']


In [55]:
print('shape', x.shape)
print('type', type(x))
print('dtype', x.dtype)

shape (2,)
type <class 'numpy.ndarray'>
dtype <U5


In [56]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [57]:
x = np.array([1, 2.5, 4], dtype=np.int64)
print(x)
print('dtype:', x.dtype)

[1 2 4]
dtype: int64


In [58]:
x = np.array([1, 2, 3, 4, 5])
np.save('my_array', x)

In [59]:
y = np.load('my_array.npy')
y

array([1, 2, 3, 4, 5])

In [60]:
X = np.zeros((3, 4))
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
X.dtype

dtype('float64')

In [62]:
X = np.ones((4, 5))
X

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
X = np.full((4, 3), 5)
X

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [64]:
X.dtype

dtype('int64')

In [65]:
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
X = np.diag([10, 20, 30, 40])
X

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [67]:
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
X = np.linspace(0, 25, 10)
X

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [69]:
X = np.linspace(0, 25, 10, endpoint=False)
X

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

In [70]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
x = np.reshape(x, (4, 5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [72]:
X = np.linspace(0, 100, 10, endpoint=False).reshape((5, 2))
X

array([[ 0., 10.],
       [20., 30.],
       [40., 50.],
       [60., 70.],
       [80., 90.]])

In [73]:
X = np.random.random((3, 3))
X

array([[0.19587378, 0.65751694, 0.18496306],
       [0.737868  , 0.65058119, 0.04402148],
       [0.11308029, 0.99565325, 0.42558583]])

In [74]:
X = np.random.randint(4, 15, (3, 2))
X

array([[ 4,  5],
       [13, 12],
       [ 7, 10]])

In [75]:
X = np.random.normal(0, 0.1, size=(1000, 1000))
X

array([[ 0.10939537, -0.21330114,  0.03235413, ..., -0.06439125,
         0.03871092,  0.02250249],
       [-0.04985499,  0.05291007, -0.05407676, ...,  0.16738949,
        -0.07289934,  0.08126799],
       [ 0.00445902,  0.00911067,  0.24941221, ...,  0.02172258,
        -0.12026449,  0.00949981],
       ...,
       [ 0.2271757 ,  0.07328377, -0.1046884 , ...,  0.11313201,
        -0.05218389,  0.02558646],
       [ 0.03746157,  0.01934421,  0.06759838, ..., -0.14800364,
        -0.14192521,  0.16761312],
       [ 0.00527866, -0.01969934, -0.01492577, ...,  0.22203616,
         0.09758364,  0.12243033]])

In [76]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [77]:
print('1st element: ', x[0])
print('2nd element: ', x[1])
print('5th element: ', x[4])

1st element:  1
2nd element:  2
5th element:  5


In [83]:
Y = np.arange(1, 10).reshape(3, 3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
W = np.delete(Y, 0, axis=0)
W

array([[4, 5, 6],
       [7, 8, 9]])

In [87]:
V = np.delete(Y, [0, 2], axis=1)
V

array([[2],
       [5],
       [8]])

In [88]:
x = np.array([1, 2, 3, 4, 5, 6])
x

array([1, 2, 3, 4, 5, 6])

In [102]:
y = np.append(x, 7)

In [103]:
z = np.append(y, [7, 8])
z

array([1, 2, 3, 4, 5, 6, 7, 7, 8])