In [1]:
import numpy as np

In [2]:
X = np.arange(1, 21).reshape(4, 5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
Y = X[1:, 2:]
Y

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [8]:
z = X[:, 2:3]
z

array([[ 3],
       [ 8],
       [13],
       [18]])