In [2]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [3]:
X = np.arange(1, 10).reshape(3, 3)
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
X[1, 1]

5

In [9]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [10]:
x = np.delete(x, [0, 4])
x

array([2, 3, 4])

In [16]:
Y = np.arange(1, 10).reshape(3, 3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
W = np.delete(Y, [0], axis=0)
W

array([[4, 5, 6],
       [7, 8, 9]])

In [18]:
Z = np.delete(Y, [0, 2], axis=1)
Z

array([[2],
       [5],
       [8]])

In [28]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [29]:
x = np.append(x, 6)
x

array([1, 2, 3, 4, 5, 6])

In [30]:
x = np.append(x, [7, 8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
Y = np.arange(1, 10).reshape(3, 3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
V = np.append(Y, [[10, 11, 12], [13, 14, 15]], axis=0)
V

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [47]:
W = np.append(Y, [[10], [11], [12]], axis=1)
W

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [48]:
x = np.array([1, 2, 5, 6, 7])
x

array([1, 2, 5, 6, 7])

In [49]:
x = np.insert(x, 2, [3, 4])
x

array([1, 2, 3, 4, 5, 6, 7])